Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.hostname = "arch-server"
  config.vm.synced_folder "../data/config", "/app"
  config.vm.synced_folder "../data/cache", "/var/cache"
  config.vm.network "private_network", ip:"192.168.50.2"
  config.vm.provision "shell", 
    inline: "sudo pacman --noconfirm -S zsh"
  config.vm.provision "shell", path: "provision.sh"

end
